# Generic single-database configuration.

[alembic]
# path to migration scripts
sqlalchemy.url = driver://user:password@localhost/dbname
script_location = alembic

# template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to zoneinfo.ZoneInfo()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field in the filename
# compared against the character length of the name supplied
# for the "message" parameter for this script
truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# When set to 'true', the localtime datetime object used to generate
# the filename of the new revision is used as the `date_` context
# variable in the ``script.py.mako`` template.  This is useful in an
# environment where it's desired to have consistent timestamps
# rather than every developmer's local time.
# sqlalchemy_module_name=sqlalchemy
# sqlalchemy_driver_name=postgresql

# set to 'false' in order to skip the automatic
# generation of new migration scripts' ``down()`` calls
# when revision scripts are generated. The default is 'true'
# populate_empty_migrations = true

# logging configuration
# Loggers to configure, plus their level
# [loggers]
# keys = sqlalchemy.engine,sqlalchemy.pool,sqlalchemy

# [handlers]
# keys = console

# [formatters]
# keys = generic

# [logger_root]
# level = WARN
# handlers = console

# [logger_sqlalchemy.engine]
# level = INFO
# handlers =
# qualname = sqlalchemy.engine

# [logger_sqlalchemy.pool]
# level = INFO
# handlers =
# qualname = sqlalchemy.pool

# [logger_alembic]
# level = INFO
# handlers =
# qualname = alembic

# [handler_console]
# class = StreamHandler
# args = (sys.stderr,)
# level = NOTSET
# formatter = generic

# [formatter_generic]
# format = %(levelname)-5.5s [%(name)s] %(message)s
# datefmt = %H:%M:%S
