"""Initial migration

Revision ID: 2f860577884a
Revises: 
Create Date: 2026-04-13 10:01:48.326901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f860577884a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_pkey'),
    sa.UniqueConstraint('username', name='auth_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_auth_id', 'auth', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_id', table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###
